### ISSUE TITLE
Share directories from host->guest via qemu:-virtfs, osx:mount_p9 

### ISSUE THREAD

**Issue by sck** [sickcodes/Docker-OSX#52]
I was looking into getting NFS working but then I came across this much more convenient way: in the qemu command-line options add:
```
-virtfs local,path=<path>,mount_tag=<volume name>,security_model=passthrough,id=<id>
```

(`<id>` can be the same as `<volume name>`)

and then in OSX:
```
10.14# mount_9p # Will automount all the volumes added via -virtfs
```
```
10.15# mount_9p <volume name> # Since Catalina the volumes to be mounted need to be named

```
I think mount_9p was added in Mojave (10.14)

**Comment by sickcodes** [comment]
You can use the


`-e EXTRA=“-somearg”` to add qemu args

**Comment by sickcodes** [comment]
This is great btw, can I add this to the repo?

**Comment by sck** [comment]
Yeah, this is why I documented it here...  I thought NFS is much too complicated to use inside docker, with the required kernel support and all, mount_9p is straightforward.  Makes build servers much more straightforward, along with the automatic booting from the macos disk :)

**Comment by sickcodes** [comment]
Thanks for this btw, just used it myself!

**Comment by mmausler** [comment]
For anyone else trying to set up a share directory between guest and host, here is what ended up working for me. I had to add my host directory as a docker volume, then reference the docker volume path in the virtfs command options.

`
docker run \
--device /dev/kvm \
--device /dev/snd \
-p 50922:10022 \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v /mnt/your_host_local_folder_here:/mnt/hostshare \
-e "DISPLAY=${DISPLAY:-:0.0}" \
-e EXTRA="-virtfs local,path=/mnt/hostshare,mount_tag=hostshare,security_model=passthrough,id=hostshare" \
yourimage
`

Since the virtfs passthrough uses host permissions on all files in the share directory, you can change the OS X user to the same ID as your host user ID and read/write should work as expected. This post was helpful in that regard 
https://www.inteller.net/notes/change-user-id-on-snow-leopard

**Comment by thematrixdev** [comment]
Thank you very much! I can find the parameter to mount in QEMU finally.

May I know where to find the mounted directory inside Mac-OS?

> For anyone else trying to set up a share directory between guest and host, here is what ended up working for me. I had to add my host directory as a docker volume, then reference the docker volume path in the virtfs command options.
> 
> ```
> docker run \
> --device /dev/kvm \
> --device /dev/snd \
> -p 50922:10022 \
> -v /tmp/.X11-unix:/tmp/.X11-unix \
> -v /mnt/your_host_local_folder_here:/mnt/hostshare \
> -e "DISPLAY=${DISPLAY:-:0.0}" \
> -e EXTRA="-virtfs local,path=/mnt/hostshare,mount_tag=hostshare,security_model=passthrough,id=hostshare" \
> yourimage
> ```
> 
> Since the virtfs passthrough uses host permissions on all files in the share directory, you can change the OS X user to the same ID as your host user ID and read/write should work as expected. This post was helpful in that regard
> https://www.inteller.net/notes/change-user-id-on-snow-leopard

**Comment by thematrixdev** [comment]
Is it possible to mount a directory as if it is a hard drive in OSX?
i.e. The mounted directory is shown in "Disk Utility" in OSX.
Thanks.

**Comment by coppercash** [comment]
I tried `mount_9p` several months ago.
But the performance was disappointing.
I put my source files (an iOS project) on the shared drive, and tried to build from there.
It was obviously much slower than on a native drive.
Even worse, it crashed at some middle point in the building process.
I couldn't find more relative information on the Internet and stopped trying.
I hope it was just my case.
Because directory sharing is so convenient and wanted.

**Comment by sickcodes** [comment]
Working to implement the solutions mentioned in this issue now!

**Comment by sickcodes** [comment]
```bash
SHARE=/home/user/test/1px/

docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -v "${PWD}/mac_hdd_ng.img:/home/arch/OSX-KVM/mac_hdd_ng.img" \
    -v "${SHARE}:/mnt/hostshare" \
    -e OSX_COMMANDS="echo alpine | sudo -S mount_9p hostshare && /bin/bash" \
    -e EXTRA="-virtfs local,path=/mnt/hostshare,mount_tag=hostshare,security_model=passthrough,id=hostshare" \
    sickcodes/docker-osx:auto

```

**Comment by gombosg** [comment]
@sickcodes actually this (https://github.com/sickcodes/Docker-OSX/issues/52#issuecomment-743473409) is very important to get sharing work both ways. Can I create a PR to add a link to the docs?

**Comment by manang** [comment]
I tried to change the uuid of the user from 501 to 1001 (it is the uuid of my user on my host vm). I'm not able to write on the shared disk.
do you know how I can solve it?
Thanks
