### ISSUE TITLE
Does "Debug View Hierarchy" in Xcode work?

### ISSUE THREAD

**Issue by coppercash** [sickcodes/Docker-OSX#99]
Hi, thanks for the awesome work.

I have been using [macOS-Simple-KVM](https://github.com/foxlet/macOS-Simple-KVM) for quite a while.

Everything (maybe not everything) works pretty well, except for one function offered in Xcode – **Debug View Hierarchy**.
The button to trigger that function looks like this:

![debug_view_hierarchy](https://user-images.githubusercontent.com/3679052/96712624-000f6180-13d2-11eb-8c5d-1fe321aa24a0.png)

In my current kvm, after I trigger this function, it shows me nothing but a blank background.

After some [digging](https://stackoverflow.com/questions/43795674/mac-sierra-10-12-use-xcode-to-debug-view-hierarchy-get-empty-not-show-the-view/61689359#61689359), I found it may be related to the lacking of OpenGL.

I am planning to migrate to Docker-OSX. But before that, I'd like to know if **Debug View Hierarchy** works within Docker-OSX.

Thanks.

**Comment by sickcodes** [comment]
You can test it out pretty quickyly, make a copy of you .img and insert it into the container as per the readme.

All the repo's use the same files :)

If you haven't used Docker before, just follow the steps at the top of the readme.

When it boots, `docker ps`, get the id of the container.

`docker inspect id | grep Upper`

and overwrite the .img file in that directory with your existing .img

Then `docker start id`

Use a copy tho because I don't wanna hurt your existing .img

**Comment by coppercash** [comment]
Thanks for the suggestion.
Frankly, that doesn't sound very easy to me.
I plan to take the action when Big Sur gets released (likely before November).
So, if **Debug View Hierarchy** doesn't work, at least I will have the new macOS. 🤪

**Comment by coppercash** [comment]
Confirmed.
It doesn't work.
Just a blank background.
It seems OpenGL is mandatory.
Closing.
